CREATE TABLE `wcvp_new` (
`wfo_id` varchar(14) DEFAULT NULL,
`plant_name_id` int(6) NOT NULL PRIMARY KEY,
`ipni_id` varchar(20),
`taxon_rank` text,
`taxon_status` text,
`family` varchar(35),
`genus_hybrid` text,
`genus` varchar(35),
`species_hybrid` text,
`species` varchar(45),
`infraspecific_rank` text,
`infraspecies` text,
`parenthetical_author` text,
`primary_author` text,
`publication_author` text,
`place_of_publication` text,
`volume_and_page` text,
`first_published` text,
`nomenclatural_remarks` text,
`geographic_area` text,
`lifeform_description` text,
`climate_description` text,
`taxon_name` text,
`taxon_authors` text,
`accepted_plant_name_id` text,
`basionym_plant_name_id` text,
`replaced_synonym_author` text,
`homotypic_synonym` text,
`parent_plant_name_id` text,
`powo_id` text,
`hybrid_formula` text,
`reviewed` text,
`hash` varchar(32),
  KEY `wfo_id` (`wfo_id`) USING BTREE,
  KEY `family` (`family`) USING BTREE,
  KEY `genus` (`genus`) USING BTREE,
  KEY `species` (`species`) USING BTREE,
  KEY `hash` (`hash`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
